steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/webapp-test-project-487812/tandem-backend:latest'
      - '.'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/tandem-backend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - run
      - --filename=.
      - --image=gcr.io/webapp-test-project-487812/tandem-backend:latest
      - --location=europe-west3
      - --namespace=default

images:
  - 'gcr.io/webapp-test-project-487812/tandem-backend:latest'

options:
  machineType: 'N1_HIGHCPU_8'
